### ISSUE TITLE
Sync from upstream

### ISSUE THREAD

**Issue by andrews05** [conor42/fxz#4]
Afaik, there's no easy way to build this on a Mac, since Macs don't have autotools. Upstream has added CMake support though, so if you can update with the latest changes it should become possible.

**Comment by tansy** [comment]
> Macs don't have autotools

Is source with built configure script going to be of any help to you?

**Comment by andrews05** [comment]
Yes, that would be even better.

**Comment by tansy** [comment]
Here you have fxz-1.1.0alpha with configure script built (md5: `f407462c7da5ade87d8f444cce7e1896  fxz-1.1.0alpha+configure.tar.xz`). Test it and share the impression.

If @conor42 wants to use it as release, feel free.

I didn't attach it to the post as it weighs almost 800k. Instead I put it **[here](https://files.fm/f/xwmtz9gyw)** on temporary internet storage. It will be deleted in 2 months.

**Comment by andrews05** [comment]
Thank you, that works!
Would be really helpful to have this published here on GH.

**Comment by tansy** [comment]
That's maintainer's question. Only he can put it in releases or something.

**Comment by conor42** [comment]
Thanks for your input guys. I'll have time to sort things out here between Christmas and the new year.

**Comment by conor42** [comment]
That should do it. The CMake build seems to work, though it doesn't install the .so shared library, only a static one (haven't checked if it's supposed to). Everything needs a bit more testing before a new alpha release.

**Comment by tansy** [comment]
What about autotools configured one put [here](https://files.fm/f/xwmtz9gyw)? It's the same 1.1.0a version with configuration script generated. You could use it as current release, it's the same source, for the time being.

**Comment by andrews05** [comment]
@conor42 Thanks heaps for updating, the cmake works great! I'm only interested in static anyway.
The configure script by itself doesn't work though as it's missing some files in the build-aux folder. Not worried about that though since the cmake works - feel free to remove the configure script.

**Comment by tansy** [comment]
Nothing is missing, everything is in the [package](https://files.fm/f/xwmtz9gyw). It's a [release](https://github.com/conor42/fxz/releases/tag/v1.1.0alpha) version with configure script (and all its dependencies).

**Comment by andrews05** [comment]
@tansy Yes, that package is complete. I was referring to the configure script that conor added here to the repo.

**Comment by tansy** [comment]
Understood.
